/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // 自动生成侧边栏（根据文件夹结构）
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
